#!/bin/bash
set -e

docker build -t docker-machine .

docker run -it \
    -e BUILDTAGS=${BUILDTAGS} \
    -p 8000:8000 \
    --rm docker-machine \
    ./script/generate-coverage serve /go/src/github.com/docker/machine
