#!/bin/sh
set -e

ARGS=$@
if [ -z "$ARGS" ]; then
    ARGS="./libmachine/... ./commands/... ./drivers/..."
fi

echo $ARGS

docker build -t docker-machine .
exec docker run --rm docker-machine godep go test -race -v -short $ARGS
